### ISSUE TITLE
"Keep Warm" ping to Replicate API to eliminate cold start issue

### ISSUE THREAD

**Issue by danwritecode** [danwritecode/AiKu#35]
The cold start time on the replicate API is brutal. We should setup a service to ping it every 10 minutes or so (may have to experiment to find good balance).

**Comment by adragione** [comment]
New codebase started for this at the following Github repo:

https://github.com/adragione/AiKu-BEND.git

**Comment by adragione** [comment]
Code review of v1 by @danwritecode requested on following pull request:

https://github.com/adragione/AiKu-BEND/pull/1

**Comment by adragione** [comment]
Few changes made today; once pull request is reviewed by @danwritecode and merged, I'll close out this issue/feature.

**Comment by adragione** [comment]
Made final revisions based on @danwritecode code review; merged into main and currently deployed on DellaLabs servers. Process will fire off an API call every 30 minutes.
